# Generated by Django 3.0 on 2019-12-15 20:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_job_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
