# Generated by Django 3.0 on 2019-12-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191215_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='dependencies',
            field=models.CharField(blank=True, default='', help_text='a list of job names this job depends on', max_length=1024),
        ),
    ]
