# Generated by Django 3.0 on 2020-04-23 07:56

from django.db import migrations
import jeeves.util


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20191215_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metadata',
            field=jeeves.util.JsonFieldTransitionHelper(default=dict),
        ),
        migrations.AlterField(
            model_name='build',
            name='metadata',
            field=jeeves.util.JsonFieldTransitionHelper(default=dict),
        ),
    ]
