# Generated by Django 3.0 on 2020-04-23 07:25

from django.db import migrations, models
import jeeves.util


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20191215_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtarget',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationmetadata',
            name='data',
            field=jeeves.util.JsonFieldTransitionHelper(default=dict),
        ),
    ]
